import { Geist, Geist_Mono } from "next/font/google";
import { Plus_Jakarta_Sans, Manrope } from "next/font/google";
import "./globals.css";
import PillNavbar from "@/components/shared/Navbar";
import Background from "@/components/shared/Background";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${plusJakartaSans.variable}  ${manrope.variable}   ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=block"
          rel="stylesheet"
        />
      </head>
      <body  className="min-h-full min-w-0 flex flex-col overflow-x-clip">
        
       
        <PillNavbar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
